# .github/workflows/deploy.yml
name: Deploy

on:
  push:
    branches: 
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      
    - name: Set environment variables
      run: |
        BRANCH=${GITHUB_REF#refs/heads/}
        echo "BRANCH=$BRANCH" >> $GITHUB_ENV
        echo "Detected branch: $BRANCH"
        
    - name: Download latest artifact
      uses: actions/download-artifact@v4
      with:
        name: build-files
        path: dist/
        
    - name: Deploy to environment
      run: |
        echo "Current branch: ${{ env.BRANCH }}"
        
        if [[ "${{ env.BRANCH }}" == "main" ]]; then
          echo "Deploying to PRODUCTION environment..."
          cat dist/build.txt || echo "No build.txt found"
          echo "Production deployment completed!"
        elif [[ "${{ env.BRANCH }}" == "develop" ]]; then
          echo "Deploying to STAGING environment..."
          cat dist/build.txt || echo "No build.txt found"
          echo "Staging deployment completed!"
        else
          echo "Unknown branch: ${{ env.BRANCH }}"
          exit 1
        fi