# .github/workflows/build.yml
name: Build

on:
  push:
    branches: 
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Project
      run: |
        echo "Starting build process..."
        echo "Building project on branch: ${GITHUB_REF#refs/heads/}"
        echo "Build completed!"
        
    - name: Create build artifact
      run: |
        mkdir -p dist
        echo "Build from ${GITHUB_REF#refs/heads/} branch at $(date)" > dist/build.txt
        
    - name: Upload build result
      uses: actions/upload-artifact@v4
      with:
        name: build-files-${GITHUB_REF#refs/heads/}
        path: dist/
        retention-days: 1