# .github/workflows/build.yml
name: Build

on:
  push:
    branches: 
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set branch name
      run: echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV
    
    - name: Build Project
      run: |
        echo "Starting build process..."
        echo "Building project on branch: ${{ env.BRANCH_NAME }}"
        echo "Build completed!"
        
    - name: Create build artifact
      run: |
        mkdir -p dist
        echo "Build from ${{ env.BRANCH_NAME }} branch at $(date)" > dist/build.txt
        
    - name: Upload build result
      uses: actions/upload-artifact@v4
      with:
        name: build-files-${{ env.BRANCH_NAME }}
        path: dist/
        retention-days: 1