# .github/workflows/deploy.yml
name: Deploy

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
    branches: [ main, develop ]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    # Checkout repository terlebih dahulu
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.workflow_run.head_branch }}
        fetch-depth: 0  # Mengambil semua history commit
        
    - name: Download artifact from build workflow
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: build.yml
        name: build-files
        path: dist/
        workflow_conclusion: success
        run_id: ${{ github.event.workflow_run.id }}
        
    - name: List downloaded files
      run: ls -la dist/
        
    - name: Deploy to environment
      run: |
        # Get latest commit hash
        LATEST_COMMIT=$(git rev-parse HEAD)
        echo "Latest commit: $LATEST_COMMIT"
        
        # Menggunakan head_branch dari workflow_run event
        if [[ ${{ github.event.workflow_run.head_branch }} == 'main' ]]; then
          echo "Deploying to PRODUCTION environment..."
          echo "Commit: $LATEST_COMMIT"
          cat dist/build.txt
          echo "Production deployment completed!"
        elif [[ ${{ github.event.workflow_run.head_branch }} == 'develop' ]]; then
          echo "Deploying to STAGING environment..."
          echo "Commit: $LATEST_COMMIT"
          cat dist/build.txt
          echo "Staging deployment completed!"
        fi