# .github/workflows/deploy.yml
name: Deploy

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
    branches: [ main, develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Download build artifact
      uses: actions/download-artifact@v2
      with:
        name: build-files
        path: dist/
        
    - name: Deploy to environment
      run: |
        if [[ $GITHUB_REF == 'refs/heads/main' ]]; then
          echo "Deploying to PRODUCTION environment..."
          echo "Production deployment completed!"
        elif [[ $GITHUB_REF == 'refs/heads/develop' ]]; then
          echo "Deploying to STAGING environment..."
          echo "Staging deployment completed!"
        fi