# .github/workflows/deploy.yml
name: Deploy

on:
  push:
    branches: 
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set branch name
      run: echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV
    
    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: build-files-${{ env.BRANCH_NAME }}
        path: dist/
        
    - name: Deploy to environment
      run: |
        echo "Deploying from branch: ${{ env.BRANCH_NAME }}"
        
        if [[ "${{ env.BRANCH_NAME }}" == "main" ]]; then
          echo "Deploying to PRODUCTION environment..."
          cat dist/build.txt || echo "No build.txt found"
          echo "Production deployment completed!"
        elif [[ "${{ env.BRANCH_NAME }}" == "develop" ]]; then
          echo "Deploying to STAGING environment..."
          cat dist/build.txt || echo "No build.txt found"
          echo "Staging deployment completed boskuhhh!"
        else
          echo "Unknown branch: ${{ env.BRANCH_NAME }}"
          exit 1
        fi