# .github/workflows/build.yml
name: Build

on:
  push:
    branches: 
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set environment variables
      run: |
        BRANCH=${GITHUB_REF#refs/heads/}
        echo "BRANCH=$BRANCH" >> $GITHUB_ENV
        echo "Building on branch: $BRANCH"
    
    - name: Build Project
      run: |
        echo "Starting build process..."
        echo "Building project on branch: ${{ env.BRANCH }}"
        echo "Build completed!"
        
    - name: Create build artifact
      run: |
        mkdir -p dist
        echo "Build from ${{ env.BRANCH }} branch at $(date)" > dist/build.txt
        
    - name: Upload build result
      uses: actions/upload-artifact@v4
      with:
        name: build-files
        path: dist/
        retention-days: 1