# .github/workflows/deploy.yml
name: Deploy

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
    branches: 
      - main
      - develop

jobs:
  deploy:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact from build workflow
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: build.yml
        name: build-files-${{ github.event.workflow_run.head_sha }}
        path: dist/
        workflow_conclusion: success
        run_id: ${{ github.event.workflow_run.id }}
        
    - name: Deploy to environment
      run: |
        BRANCH="${{ github.event.workflow_run.head_branch }}"
        echo "Deploying from branch: $BRANCH"
        echo "Commit SHA: ${{ github.event.workflow_run.head_sha }}"
        
        echo "Content of build.txt:"
        cat dist/build.txt
        
        if [[ $BRANCH == "main" ]]; then
          echo "Deploying to PRODUCTION environment..."
          echo "Production deployment completed!"
        elif [[ $BRANCH == "develop" ]]; then
          echo "Deploying to STAGING environment..."
          echo "Staging deployment completed boskuuuh!"
        fi