# .github/workflows/deploy.yml
name: Deploy

on:
  push:
    branches: 
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: build-files-${GITHUB_REF#refs/heads/}
        path: dist/
        
    - name: Deploy to environment
      run: |
        BRANCH=${GITHUB_REF#refs/heads/}
        echo "Deploying from branch: $BRANCH"
        
        if [[ "$BRANCH" == "main" ]]; then
          echo "Deploying to PRODUCTION environment..."
          cat dist/build.txt || echo "No build.txt found"
          echo "Production deployment completed!"
        elif [[ "$BRANCH" == "develop" ]]; then
          echo "Deploying to STAGING environment..."
          cat dist/build.txt || echo "No build.txt found"
          echo "Staging deployment completed!"
        else
          echo "Unknown branch: $BRANCH"
          exit 1
        fi